# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
highlighter: pygments
markdown: redcarpet

name: "[ antoinealb.net ]"
description: A blog about robotics, embedded software and Linux

author:
  name: Antoine
  email: antoinea101@gmail.com
  github: antoinealb
  twitter: antoinealb
  bio: Robotics enthusiast studying Microengineering in Lausanne, Switzerland


logo: false

# Exclude our ruby stuff
exclude: [README.md .bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]

# Details for the RSS feed generator
url: 'http://antoinealb.net'
baseurl: '/'
