# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Antoine's blog

description: A blog about robotics, embedded software and Linux
author:
  name: Antoine Albertelli
  email: antoinea101@gmail.com
  github: antoinealb
  twitter: antoinealb
  bio: Robotics enthusiast studying Microengineering in Lausanne, Switzerland
  email_md5: 1d2591a8b213644c8dfe38098e71b46d

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
